root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/gateway ./cmd/gateway"
  bin = "./tmp/gateway"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 1000

[misc]
  clean_on_exit = true
