[package]
name = "noisereduce"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
nnnoiseless = "0.5"

[profile.release]
opt-level = 3
lto = true
